"""The derived-state substrate — the single registry of every derived-committed artifact the engine
regenerates from source, with one generator, one presence rule, and one drift check per member.

Before this module the same set was enumerated in several drifting places: `pr_reconcile.MEMBERS` (a
2-tuple, regenerated by a hard-coded subprocess loop), `module_manager.REGENERATED_DERIVED` (a 3-tuple,
regenerated by an in-process resolver whose failures were swallowed), `overlay_disclosure` reaching into
that tuple, and the release workflow regenerating a 2-file subset of its own. Each drift was a latent way
for a derived file to be missed at one lifecycle boundary but not another. This module is the one owner of
that set, so a new derived artifact registers in ONE place and reaches every boundary.

Ownership boundary (honest scope): this registry owns the derived-committed files that the reconcile,
upgrade, arrival, and release boundaries regenerate — self-map, knowledge graph, and the (optional)
product-spec-matrix. It does NOT claim to be the only list of index files anywhere: sites that enumerate a
DIFFERENT set for a different purpose (e.g. a CI-required-indexes gate, a PR-body copy) are left as-is; the
single-source test in `test_derived_state.py` binds only the consumers this module migrates.

Two dispatch conventions are preserved, one per caller need:
  - import   (default): calls the generator in-process. Sources are read through `validate.ENGINE_DIR`, so
    a caller that has redirected that global (the upgrade tail, arrival) regenerates the tree it is working
    on. Fast and unit-testable.
  - subprocess         : shells the generator tool with the tree as `cwd`, so the child process initializes
    its own `validate.ENGINE_DIR` from the tool's location. This is what `pr_reconcile` and the demos need
    to regenerate a throwaway repo faithfully.

Regeneration returns an EXPLICIT per-member result (never a swallowed exception, never a bare bool that
hides which member failed). Callers on the hot upgrade/arrival path treat a `failed` result as ADVISORY —
the downstream drift gate (self-map-drift / knowledge-coverage / the matrix's own check) remains the
authority that refuses — so replacing the old silent swallow does not newly refuse an upgrade whose
committed output is already canonical.
"""

from __future__ import annotations

import os
import subprocess
import sys
from dataclasses import dataclass
from typing import Callable, Iterable, Optional

import validate
import engine_write


@dataclass(frozen=True)
class DerivedMember:
    """One derived-committed artifact. Pure data; the generator/check callables are resolved lazily by
    `_resolve_generate` / `_resolve_check` (keyed on `path`) so the OPTIONAL product-design import stays
    guarded and absent-is-expected."""

    path: str                              # repo-relative committed artifact, e.g. ".engine/self-map.md"
    tool: str                              # CLI path under .engine/tools for subprocess dispatch
    check_rule: str                        # the gating drift-check rule id
    reconcile: bool                        # participates in pr_reconcile's spurious-conflict set
    release: bool                          # regenerated in the release-cut PR
    optional_module: Optional[str] = None  # importing module that must be present, else None (core)


# The v1 roster. self-map and graph are core and always present; the product-spec-matrix is supplied by the
# OPTIONAL product-design module and derives from the deployment's own docs/spec, so it is present only where
# both the module and a settled spec exist (see `_present`).
MEMBERS: tuple[DerivedMember, ...] = (
    DerivedMember(".engine/self-map.md", "self_map.py",
                  "engine/check/self-map-drift", reconcile=True, release=True),
    DerivedMember(".engine/knowledge/graph.json", "knowledge_gen.py",
                  "engine/check/knowledge-coverage", reconcile=True, release=True),
    DerivedMember(".engine/product-spec-matrix.json", "product_design/obligation_matrix.py",
                  "engine/check/product-spec-matrix", reconcile=True, release=False,
                  optional_module="product-design"),
)
# Deliberately EXCLUDED — do not re-add without cause:
#   - uv default-groups: a FRAGMENT of authored .engine/pyproject.toml (not a whole derived file), a
#     different generator signature (sync_groups, an in-place line rewrite), and pyproject is a floor file.
#     It keeps its own `uv-group-drift` check + `module_manager.sync_groups`.
#   - .engine/provisioning/module-surfaces.json: a SOURCE-repo catalog regenerated when tool files change,
#     NOT a per-deployment derived artifact (a deployment ships it unchanged so it can recognise a declined
#     module's surfaces). Regenerated by module_surfaces.py at the integrate boundary, not by this substrate.
#   - authored surface-catalog.json / module-catalog.json (source of truth, not generated).
#   - .engine/knowledge/index.sqlite (an uncommitted local cache that self-heals).


@dataclass(frozen=True)
class MemberResult:
    """The explicit per-member outcome of a regenerate pass — never a swallowed exception."""

    path: str
    status: str            # regenerated | unchanged | skipped-absent | skipped-symlink
                           #             | skipped-no-generator | failed
    changed: bool
    detail: str
    error: Optional[str] = None


@dataclass(frozen=True)
class DriftResult:
    """The per-member outcome of a verify pass."""

    path: str
    check_rule: str
    status: str            # in-sync | drift | skipped-absent | error
    message: str


_DRIFT_SEVERITIES = {"hard", "serious", "blocking", "warn", "error"}


# ---- generator / check resolution (lazy, optional-guarded) -----------------------------------------

def _resolve_generate(member: DerivedMember) -> Optional[Callable]:
    """The member's `generate(path=...)` callable, or None when its optional module is absent (expected).
    An unregistered member is a MAINTENANCE bug (the roster and this resolver must stay in lockstep) and
    fails loud, never a silent skip."""
    if member.path == ".engine/self-map.md":
        import self_map
        return self_map.generate
    if member.path == ".engine/knowledge/graph.json":
        import knowledge_gen
        return knowledge_gen.generate
    if member.path == ".engine/product-spec-matrix.json":
        try:
            from product_design import obligation_matrix   # OPTIONAL: absent is EXPECTED → skip
        except ImportError:
            return None
        return obligation_matrix.generate
    raise KeyError(f"derived_state member {member.path!r} has no generator — roster/resolver drift")


def _resolve_check(member: DerivedMember) -> Optional[Callable]:
    """The member's `check(path=...)` callable, or None when its optional module is absent."""
    if member.path == ".engine/self-map.md":
        import self_map
        return self_map.check
    if member.path == ".engine/knowledge/graph.json":
        import knowledge_gen
        return knowledge_gen.check
    if member.path == ".engine/product-spec-matrix.json":
        try:
            from product_design import obligation_matrix
        except ImportError:
            return None
        return obligation_matrix.check
    raise KeyError(f"derived_state member {member.path!r} has no check — roster/resolver drift")


# ---- selection --------------------------------------------------------------------------------------

def _engine_dir(root: Optional[str]) -> str:
    return validate.ENGINE_DIR if root is None else os.path.join(root, ".engine")


def _target(member: DerivedMember, engine_dir: str) -> str:
    # ".engine/knowledge/graph.json" -> <engine_dir>/knowledge/graph.json
    return os.path.join(engine_dir, *member.path.split("/")[1:])


def _present(member: DerivedMember, root: Optional[str]) -> bool:
    """A member is present iff its committed file exists AND its generator is resolvable (its optional
    module is installed). Gating on generator-resolvability — not mere file presence — is what keeps a
    present-file / absent-generator deployment OUT of the reconcile set: such a conflict must classify
    needs-manual and refuse, never append-merge and then discover the regen was skipped."""
    target = _target(member, _engine_dir(root))
    return os.path.isfile(target) and _resolve_generate(member) is not None


def members(*, reconcile: Optional[bool] = None, release: Optional[bool] = None,
            present_root: Optional[str] = None) -> tuple[DerivedMember, ...]:
    """The registry, optionally filtered. `present_root` set → only members present (file + resolvable
    generator) under that root. All-None → the full static roster."""
    out = MEMBERS
    if reconcile is not None:
        out = tuple(m for m in out if m.reconcile is reconcile)
    if release is not None:
        out = tuple(m for m in out if m.release is release)
    if present_root is not None:
        out = tuple(m for m in out if _present(m, present_root))
    return out


def paths(**kw) -> tuple[str, ...]:
    """The member paths — the single-source replacement for the old hard-coded tuples."""
    return tuple(m.path for m in members(**kw))


def _select(members_arg: Optional[Iterable[str]]) -> tuple[DerivedMember, ...]:
    if members_arg is None:
        return MEMBERS
    wanted = set(members_arg)
    return tuple(m for m in MEMBERS if m.path in wanted)


# ---- regeneration ----------------------------------------------------------------------------------

def regenerate(members_arg: Optional[Iterable[str]] = None, *, root: Optional[str] = None,
               dispatch: str = "import") -> list[MemberResult]:
    """Regenerate each requested member (default: all) and return an EXPLICIT per-member result. A
    generator exception yields status='failed' with the error captured — never swallowed, never a raise
    that aborts its siblings. import dispatch reads sources through validate.ENGINE_DIR (redirect it to
    target another tree); subprocess dispatch shells each tool with the tree as cwd (pr_reconcile / demo
    fidelity)."""
    selected = _select(members_arg)
    if dispatch == "subprocess":
        return [_regen_one_subprocess(m, root) for m in selected]
    if dispatch == "import":
        return [_regen_one_import(m) for m in selected]
    raise ValueError(f"unknown dispatch {dispatch!r} (expected 'import' or 'subprocess')")


def _regen_one_import(member: DerivedMember) -> MemberResult:
    target = _target(member, validate.ENGINE_DIR)
    if not os.path.isfile(target):
        return MemberResult(member.path, "skipped-absent", False,
                            "the tree does not carry this index — not fabricated")
    # os.path.isfile follows a symlink; refuse to regenerate THROUGH a live symlink (an out-of-tree write).
    if engine_write.write_through_symlink_reason(target, validate.ROOT):
        return MemberResult(member.path, "skipped-symlink", False,
                            "target is a symlink out of the tree — regen skipped, drift gate backstops")
    gen = _resolve_generate(member)
    if gen is None:
        return MemberResult(member.path, "skipped-no-generator", False,
                            f"optional module {member.optional_module!r} absent — nothing to regenerate")
    try:
        finding = gen(path=target)
    except Exception as exc:  # noqa: BLE001 — surfaced as a per-member result, never a traceback
        return MemberResult(member.path, "failed", False, "regeneration raised", error=repr(exc))
    message = (finding or {}).get("message", "") if isinstance(finding, dict) else ""
    changed = "already up to date" not in message
    return MemberResult(member.path, "regenerated" if changed else "unchanged", changed,
                        message or "regenerated")


def _regen_one_subprocess(member: DerivedMember, root: Optional[str]) -> MemberResult:
    base = root if root is not None else validate.ROOT
    target = os.path.join(base, member.path)
    if not os.path.isfile(target):
        return MemberResult(member.path, "skipped-absent", False, "the tree does not carry this index")
    tool_path = os.path.join(base, ".engine", "tools", member.tool)
    if not os.path.isfile(tool_path):
        return MemberResult(member.path, "skipped-no-generator", False,
                            f"generator tool {member.tool} absent in the tree")
    try:
        proc = subprocess.run([sys.executable, tool_path, "generate"], capture_output=True, text=True,
                              timeout=300, check=False, cwd=base)
    except Exception as exc:  # noqa: BLE001 — a hung (TimeoutExpired) or un-spawnable (OSError) generator is
        # a per-member FAILURE, never a raise: an uncaught exception here would propagate past a caller that
        # has already merged (pr_reconcile._execute_bring_up_to_date), skipping its reset --hard cleanup and
        # the coordinator's admission release — the same never-swallowed-never-raise contract the import path
        # honours (mirrors the pre-refactor pr_reconcile._regen_members `except: return False`).
        return MemberResult(member.path, "failed", False, "generator subprocess raised", error=repr(exc))
    if proc.returncode != 0:
        return MemberResult(member.path, "failed", False, "generator exited non-zero",
                            error=(proc.stderr or proc.stdout or "").strip()[:500])
    return MemberResult(member.path, "regenerated", True, (proc.stdout or "regenerated").strip()[:200])


# ---- verification ----------------------------------------------------------------------------------

def verify(members_arg: Optional[Iterable[str]] = None, *, root: Optional[str] = None) -> list[DriftResult]:
    """Run each member's drift check over the SAME roster regenerate() owns (so repair converges). Read
    only. An absent member is 'skipped-absent'; a check raising is 'error'."""
    results: list[DriftResult] = []
    for member in _select(members_arg):
        target = _target(member, _engine_dir(root))
        if not os.path.isfile(target):
            results.append(DriftResult(member.path, member.check_rule, "skipped-absent", "index not present"))
            continue
        check = _resolve_check(member)
        if check is None:
            results.append(DriftResult(member.path, member.check_rule, "skipped-absent",
                                       f"optional module {member.optional_module!r} absent"))
            continue
        try:
            finding = check(path=target)
        except Exception as exc:  # noqa: BLE001
            results.append(DriftResult(member.path, member.check_rule, "error", repr(exc)))
            continue
        severity = (finding or {}).get("severity", "") if isinstance(finding, dict) else ""
        message = (finding or {}).get("message", "") if isinstance(finding, dict) else ""
        status = "drift" if severity in _DRIFT_SEVERITIES else "in-sync"
        results.append(DriftResult(member.path, member.check_rule, status, message or status))
    return results


def repair(members_arg: Optional[Iterable[str]] = None, *, root: Optional[str] = None
           ) -> tuple[list[DriftResult], list[MemberResult], list[DriftResult]]:
    """The explicit drift-repair round-trip: verify → regenerate the drifted members → re-verify. The
    mutating counterpart to boot's read-only relay (boot detects and offers; repair performs)."""
    before = verify(members_arg, root=root)
    drifted = [d.path for d in before if d.status == "drift"]
    regen = regenerate(drifted, root=root) if drifted else []
    after = verify(members_arg, root=root)
    return before, regen, after


# ---- CLI -------------------------------------------------------------------------------------------

def _cli(argv: list[str]) -> int:
    import argparse
    parser = argparse.ArgumentParser(description="The derived-state substrate: one registry of the "
                                                 "derived-committed artifacts, with regenerate/verify/repair.")
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("members", help="print the registry")
    p_regen = sub.add_parser("regenerate", help="regenerate all present members")
    p_regen.add_argument("--release", action="store_true", help="only the release-cut subset")
    sub.add_parser("verify", help="report per-member drift (read-only)")
    sub.add_parser("repair", help="verify → regenerate drifted → re-verify")
    args = parser.parse_args(argv)

    if args.cmd == "members":
        print("The derived-committed files the Engine regenerates from source:")
        for m in MEMBERS:
            here = "present here" if _present(m, validate.ROOT) else "not present here"
            roles = [r for r, on in (("reconciled on a spurious conflict", m.reconcile),
                                     ("refreshed at release", m.release)) if on]
            print(f"  - {m.path} — {here}; {', '.join(roles)}; drift check: {m.check_rule}")
        return 0
    if args.cmd == "regenerate":
        sel = paths(release=True) if args.release else None
        results = regenerate(sel)
        for r in results:
            print(f"{r.status}\t{r.path}\t{r.detail}" + (f"\t{r.error}" if r.error else ""))
        return 1 if any(r.status == "failed" for r in results) else 0
    if args.cmd == "verify":
        results = verify()
        for r in results:
            print(f"{r.status}\t{r.path}\t{r.message}")
        return 1 if any(r.status in ("drift", "error") for r in results) else 0
    if args.cmd == "repair":
        before, regen, after = repair()
        for r in regen:
            print(f"regenerated\t{r.status}\t{r.path}")
        still = [d for d in after if d.status in ("drift", "error")]
        for d in still:
            print(f"UNRESOLVED\t{d.path}\t{d.message}")
        return 1 if still else 0
    return 2


if __name__ == "__main__":
    raise SystemExit(_cli(sys.argv[1:]))
